FROM node:22-alpine AS base

RUN corepack enable

FROM base AS deps

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn/

RUN yarn install --immutable --frozen-lockfile

FROM base AS builder

ARG ARG_APP_NAME

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN cd apps/$ARG_APP_NAME && yarn nx build

FROM nginx:alpine AS runner

ARG ARG_APP_NAME

COPY --from=builder /app/dist/apps/$ARG_APP_NAME /usr/share/nginx/html
